---
kind: pipeline
type: docker
name: web

steps:
  - name: npm install
    image: node:alpine3.10
    commands:
      - npm i --registry=https://registry.npm.taobao.org

  - name: test
    image: node:alpine3.10
    commands:
      - npm run test

  - name: build
    image: node:alpine3.10
    commands:
      - npm run build

  - name: rsync prod
    image: drillster/drone-rsync
    environment:
      RSYNC_KEY:
        from_secret: rsync_key
    settings:
      hosts:
        - 140.143.1.235
      source: .vuepress/dist/*
      target: /data
      secrets: [rsync_key]
    when:
      target:
        - prod
      event:
        - promote

  - name: rsync dev
    image: drillster/drone-rsync
    environment:
      RSYNC_KEY:
        from_secret: rsync_key
    settings:
      hosts:
        - 140.143.1.235
      source: .vuepress/dist/*
      target: /data
      secrets: [rsync_key]
    when:
      target:
        - dev
      event:
        - promote

  - name: notify
    image: curlimages/curl
    commands:
      - |
        curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=bce19711-62fa-4f9f-9f90-1dfc6f10b557' -H 'Content-Type: application/json' -d '{"msgtype": "text", "text": {"content": "ok"}}'
    when:
      status:
        - failure
        - success
